### PR TITLE
Ipb 4/knowing custody status

### PR DESCRIPTION
**Pull request by rgforsyth**
## What does this pull request do?

Adds the current location flow to the draft referral form and a start on the check your answers/referral details page. All behind a feature flag.

## What is the intent behind these changes?

To allow the ability to store current location and prison information if the user is in custody.

### CODE REVIEW

**Review by awhodgson256 — COMMENTED** [review]
A GET endpoint with a name containing "submit" suggests it should be a POST or PUT.  Is this a pattern that is used elsewhere in the app?

Specifically .... >  describe('GET /referrals/:id/submit-current-location', () => {

**Comment by rgforsyth** [comment]
This is purely due to the copydeck design asking for the url to be `submit-current-location`

**Comment by awhodgson256** [comment]
> This is purely due to the copydeck design asking for the url to be `submit-current-location`

Fair enough if there is a design reasoning...

**Review by kth13 — APPROVED** [review]
LGTM

**Pull request merged**
