### PR TITLE
Roll out dashboard pagination to 5% for providers

### PR DESCRIPTION
**Pull request by sldblog**
## What does this pull request do?

Roll out dashboard pagination to 5% for providers -- 5% of provider users will see their dashboards limited to 100 elements.

**100 page size** is projected to return in around 1 second for 50% of providers:

image

## What is the intent behind these changes?

Reverts 243da59128088c87cda66bd3248ebd4e648908d1 as caseworker sort has been re-enabled by 50187906aa387139508b45a0437b1fbf14de4fdd (a precondition for the experiment to restart)

Overall, we want to reduce unbounded queries resulting in 100% database load:
image

### CODE REVIEW

**Comment by kth13** [comment]
This PR is blocked as the caseworker sorting is still not fixed as it is returning duplicated referrals

**Comment by kth13** [comment]
This PR is unblocked now as the caseworker sorting has been fixed.

**Comment by sldblog** [comment]
Got a 👍 from the team on this going ahead

**Review by NeilLuptonMoJ — APPROVED** [review]

**Review by kth13 — APPROVED** [review]
LGTM

**Comment by sldblog** [comment]
🙌 ❤️

**Pull request merged**
