### PR TITLE
seed repo with hmpps typescript template code

### PR DESCRIPTION
**Pull request by tomsmyers**
this code is pulled from here https://github.com/brightonsbox/example-typescript-template/pull/1

but i'm told this will very shortly be moving to https://github.com/ministryofjustice/hmpps-template-typescript and will become the recommended project structure for moj express / typescript apps.

it's quite heavy for an initial commit, but we can trim this down so it's more manageable in subsequent PRs.

it provides: 

- express app with moj and gds design assets
- integration testing with cypress
- logging with bunyan
- docker image definition
- hmpps-auth login 
- local and test docker-compose configs
- linting with eslint
- redis session store
- security best practices with helmet 
- healthcheck endpoint

### CODE REVIEW

**Review by Gweaton — COMMENTED** [review]
Do you think you could add some instructions to the README for how to run the project? I've tried running `npm run start:dev` but am getting redirected to `localhost:9090` when I try to visit `localhost:3000` EDIT: Sorry, ignore me, I didn't see the README in all of these line changes!

**Comment by tomsmyers** [comment]
@Gweaton done :)

**Review by Gweaton — APPROVED** [review]
This is a good starting point - do you think it'd be at all useful if I spent some time documenting what we're using here in ADRs / the README? Would also help me to understand what's going on in the codebase...

**Comment by tomsmyers** [comment]
@Gweaton sounds good!

**Pull request merged**
