### PR TITLE
IC-1218 create page to enter number of sessions for action plan

### PR DESCRIPTION
**Pull request by tomsmyers**
## What does this pull request do?

create page to enter number of sessions for action plan

this is unfinished code - but since george and i are working on the same screens some of this code needs to be merged early.

there is some refactoring in here - sorry it's not split out into seperate commits. i was rushing.

## What is the intent behind these changes?

add the 'create action plan' form

### CODE REVIEW

**Comment by Gweaton** [comment]
I'm gonna rename the presenters on my branch to match this one, so we can get that merged in first as there's some mocking and more tests - can we leave this one as a kind of draft for now and incorporate these changes once that's done?

**Comment by tomsmyers** [comment]
> I'm gonna rename the presenters on my branch to match this one, so we can get that merged in first as there's some mocking and more tests - can we leave this one as a kind of draft for now and incorporate these changes once that's done?

sure - i'll park it for now and pick up once you have completed the first section.

**Comment by lawrence-forooghian** [comment]
@tomsmyers looks like there's some stuff to handle on here still - merge conflicts, tests, commit history. Should we put it into draft for now and then sort it out once some of the other PRs are merged?

**Comment by tomsmyers** [comment]
> @tomsmyers looks like there's some stuff to handle on here still - merge conflicts, tests, commit history. Should we put it into draft for now and then sort it out once some of the other PRs are merged?

yeh i haven't touched this in a while. was waiting for the activities page to be completed then i'll update this. it should be relatively quick to do.

**Comment by lawrence-forooghian** [comment]
I've got a version of this working on top of my changes for building the rest of the journey - let's come back and sort this PR out once I've got a PR for the first part up

**Comment by lawrence-forooghian** [comment]
Gonna close this and open a new one.

**Pull request closed without merging**
