### PR TITLE
IC-1882: Changed initial find interventions page to use 'Service user' rather than 'Service User'

### PR DESCRIPTION
**Pull request by andrewburrowsmoj**
## What does this pull request do?

Change occurrences of 'Service User' to 'Service user'

## What is the intent behind these changes?

Ensure that the user only sees 'Service user' as sentence case

Split into three parts:
3a23c1f: Changes to front end screen directly
be60a85: Change to factories
bd47688: Changes to unit tests

### CODE REVIEW

**Comment by andrewburrowsmoj** [comment]
There is an issue with github checks not updating to latest check when doing certain types of squashing... but as you can see from the individual commits the last commit had a passing circleCI run.

**Review by tomsmyers — APPROVED** [review]
thanks for this! 

looks like this requires changes in the reference data in the API. do we have to hold off on merging this until we have that change ready to go?

**Comment by sldblog** [comment]
that wording is outside our control

**Comment by sldblog** [comment]
the integration tests use a mock, right? can we change the mocks to not use the actual values we have to make it obvious it's operating on dummy data?

**Comment by andrewburrowsmoj** [comment]
> thanks for this!
> 
> looks like this requires changes in the reference data in the API. do we have to hold off on merging this until we have that change ready to go?

Yes, that has been done in this PR: https://github.com/ministryofjustice/hmpps-interventions-service/pull/321

**Comment by andrewburrowsmoj** [comment]
> the wording of the levels, outcomes is outside our control I think (we get it in a spreadsheet)

My understanding is that it is held in the database?

**Comment by andrewburrowsmoj** [comment]
> the integration tests use a mock, right? can we change the mocks to not use the actual values we have to make it obvious it's operating on dummy data?

What do you mean by this?
You mean to use something like "Dummy Desired Outcome Description 1" "Dummy Desired Outcome Description 2"?

**Pull request merged**
