### PR TITLE
Load instrumentation key on target environments

### PR DESCRIPTION
**Pull request by sldblog**
## What does this pull request do?

Load instrumentation key on target environments

`APPINSIGHTS_INSTRUMENTATIONKEY` was always unset on all environments -- this is now read from the same secret that the service uses

Switched to `APPLICATIONINSIGHTS_CONNECTION_STRING` as the service uses that same mechanism

## What is the intent behind these changes?

This will enable tracing across all interventions apps

### CODE REVIEW

**Comment by tomsmyers** [comment]
why not use the same variable - "connection string" - instead of instrumentation key in this deploy?

**Comment by sldblog** [comment]
that's much better 👍 let me do that

**Comment by sldblog** [comment]
@tomsmyers done in 5cb9d6f8e5eb7d26ea9a2142a902430a88d3f0e8

**Review by tomsmyers — APPROVED** [review]
nice - thanks!

**Comment by sldblog** [comment]
(forgot the secrets example -- no other changes)

**Pull request merged**
